algorithm_path: agents.sdrgn.SoftDRGNAgent
base_config:
- ./env.yaml
- configs/base_configs/sdrgn.yaml
batch_size: 32
buffer_capacity: 5000
burnin_episode: 1000
entropy_target_factor: 0.3
env_collide_range: 5
env_comm_range: 18
env_coverage_range: 10
env_enable_obstacle: false
env_major_point_min_distant_percent: 0.25
env_num_agent: 20
env_num_circle_obstacle: 3
env_num_grid: 200
env_num_major_point: 3
env_num_max_neighbor_agent: 5
env_num_max_neighbor_poi: 10
env_num_poi: 120
env_num_rect_obstacle: 3
env_observe_range: 13
env_static_poi: true
env_use_pixel_obs: true
env_use_square_obs: false
episode_length: 100
epsilon_decay_percent_episode: 2.0e-05
epsilon_decay_temperature: 0.0001
epsilon_exponential_decay: true
epsilon_linear_decay: false
gamma: 0.95
hidden_dim: 256
initial_epsilon: 0.9
learning_rate: 0.001
min_epsilon: 0.3
num_episodes: 200
num_head: 4
num_max_keep_ckpt: 5
scenario_path: scenarios.continuous_uav_mbs.ContinuousUAVMBS
skip_connect: true
soft_update_target_network: false
tau: 0.99
testing_action_mode: epsilon-categorical
testing_episodes: 20
testing_interval: 100
trainer_path: trainers.soft_value_based_trainer.SoftValueBasedTrainer
training_action_mode: epsilon-categorical
training_interval: 1
training_times: 4
work_dir: checkpoints/uav-mbs_sdrgn
